### ISSUE TITLE
Enabling "Extend from Into Client area" for certain process, extends to other process opened from said previous process, even though it havent been enable for them

### ISSUE THREAD

**Issue by GitExploraa** [MicaForEveryone/MicaForEveryone#137]
im using this option with qbitorrent, and when i open an explorer windows from it to choose files or something, said effect extends even to the explorer window, even though i havent enabled it for explorer, the images below show that

![image](https://user-images.githubusercontent.com/44654056/192051799-58f353ba-e5d0-494b-9404-edae02cd1af5.png)
![image](https://user-images.githubusercontent.com/44654056/192051952-20d2cc58-7a0b-47ed-878f-5a2b5d44a3e9.png)

**Comment by dongle-the-gadget** [comment]
The dialog box is hosted under qBittorrent's process, hence why the effects extend there too.

Nothing unexpected I would say.

**Comment by GitExploraa** [comment]
> The dialog box is hosted under qBittorrent's process, hence why the effects extend there too.
> 
> Nothing unexpected I would say.

i see, thank you... althought it'd be nice if it were possible to avoid this

**Comment by Yarrio69** [comment]
Add a Class rule for `#32770` and leave those settings default, the dialog window should be ignored by MicaForEveryone.

**Comment by GitExploraa** [comment]
> Add a Class rule for `#32770` and leave those settings default, the dialog window should be ignored by MicaForEveryone.

can you elaborate more please? should i just put #32770 as the class name or something when choosing?

**Comment by Yarrio69** [comment]
While MicaForEveryone app is open
- Click "Add Rule"
- Add Class Rule
- paste `#32770`
- Click Add
- Done, the Open/Save dialog won't be also affected.

**Comment by GitExploraa** [comment]
> While MicaForEveryone app is open
> 
> * Click "Add Rule"
> * Add Class Rule
> * paste `#32770` into input box
> * Click Add
> * Done, the Open/Save dialog won't be also affected.

Thanks for replying, actually i tried just this before asking and it didnt work so i thought i made a mistake along the way or something...
![image](https://user-images.githubusercontent.com/44654056/192879162-b15de7f6-461d-40e6-b978-bdf7f5c0bcb4.png)
 
and as you can see below it still shows
![image](https://user-images.githubusercontent.com/44654056/192879346-14db9c91-39bf-4b96-8961-43f159ec1820.png)

**Comment by Yarrio69** [comment]
It seems the process rule is overriding the class rule (related to #108 )

Move `qbittorrent` below `#32770` by deleting it & re-adding it.

![image](https://user-images.githubusercontent.com/63135654/193057559-93ca82bb-97cc-45ae-aba0-ca4f7d7fc3f3.png)

**Comment by GitExploraa** [comment]
> It seems the process rule is overriding the class rule (related to #108 )
> 
> Move `qbittorrent` below `#32770` by deleting it & re-adding it.
> 
> ![image](https://user-images.githubusercontent.com/63135654/193057559-93ca82bb-97cc-45ae-aba0-ca4f7d7fc3f3.png)

problem solved, you a genius, Thanks a lot
